name: Lint
run-name: ${{ github.actor }} is running ${{ github.workflow }}
on: [push]

jobs:
  trunk-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm ci
      - name: Trunk Check
        uses: trunk-io/trunk-action@v1.1.16
    