permissions: read-all
name: Test
run-name: ${{ github.actor }} is running ${{ github.workflow }}
on: [push]

jobs:
    test-cases:
        runs-on: ubuntu-latest
        steps:
            - name: Check Out Repository
              uses: actions/checkout@v4
            - name: Enable Corepack
              run: corepack enable
            - name: Use Node.js v18
              uses: actions/setup-node@v4
              with:
                  node-version: lts/Hydrogen
                  cache: yarn
            - name: Install Dependencies
              run: yarn install --immutable --immutable-cache --check-cache
            - name: Run Test Cases
              run: yarn run test
